export const HOST = "http://localhost:8000/"
export const API = "api/v1/"
export const API_LOGIN = API + "token/login"
export const SECTION = API + "section/"
export const THREAD = API + "thread/"
export const MESSAGE = API + "message/"
export const USER = API + "user/"