# Generated by Django 5.0.6 on 2024-05-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='sections',
            field=models.ManyToManyField(through='forum_app.SectionThread', to='forum_app.section', verbose_name='sections'),
        ),
        migrations.AlterField(
            model_name='section',
            name='threads',
            field=models.ManyToManyField(through='forum_app.SectionThread', to='forum_app.thread', verbose_name='threads'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
