# Generated by Django 5.0.6 on 2024-05-26 07:53

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0002_thread_sections_alter_section_threads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_body',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=500, verbose_name='message_body'),
        ),
    ]
