# Generated by Django 5.0.6 on 2024-05-26 09:12

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0003_alter_message_message_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_body',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=2000, verbose_name='message_body'),
        ),
    ]
