# Generated by Django 5.0.6 on 2024-05-27 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0005_alter_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionthread',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum_app.section', verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='sectionthread',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum_app.thread', verbose_name='thraed'),
        ),
    ]
