# Generated by Django 5.0.4 on 2024-04-29 21:22

import django.db.models.deletion
import forum_app.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
                'db_table': '"forum"."section"',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=forum_app.models.get_datetime, null=True, validators=[forum_app.models.check_created], verbose_name='created')),
                ('title', models.TextField(max_length=100, verbose_name='title')),
            ],
            options={
                'verbose_name': 'thread',
                'verbose_name_plural': 'threads',
                'db_table': '"forum"."thread"',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=forum_app.models.get_datetime, null=True, validators=[forum_app.models.check_created], verbose_name='created')),
                ('login', models.TextField(max_length=100, verbose_name='login')),
                ('password', models.TextField(max_length=100, verbose_name='password')),
                ('mail', models.TextField(max_length=100, verbose_name='mail')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': '"forum"."user"',
                'ordering': ['login'],
            },
        ),
        migrations.CreateModel(
            name='SectionThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_app.section', verbose_name='section')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_app.thread', verbose_name='thraed')),
            ],
            options={
                'verbose_name': 'relationship section thread',
                'verbose_name_plural': 'relationships section thread',
                'db_table': '"forum"."section_thread"',
                'unique_together': {('section', 'thread')},
            },
        ),
        migrations.AddField(
            model_name='section',
            name='threads',
            field=models.ManyToManyField(through='forum_app.SectionThread', to='forum_app.thread', verbose_name='thread'),
        ),
        migrations.AddField(
            model_name='thread',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum_app.user'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=forum_app.models.get_datetime, null=True, validators=[forum_app.models.check_created], verbose_name='created')),
                ('message_body', models.TextField(verbose_name='message_body')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_app.thread')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum_app.user')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'db_table': '"forum"."message"',
                'ordering': ['created'],
            },
        ),
    ]
